sudo: false
language: node_js
node_js:
- 9
branches:
  only:
  - master
deploy:
  provider: heroku
  app: ci-with-travis
  api_key:
    secure: od0UDBqtgQRaYJTznldS6YoOX4JnY8hVUoL8CXql7y7PtFXKfT1oCWsD0QfSC2J4tnLsB/7IEyyj+FyTmKBO3Pc3rqztw17NTJwIMwTm/Tu0VZavqPsepf+eADZ1V1sTaiYkL1D7E/ZC6gbcsZ5KKGXChbntLIkYc2VNcjpJ1FjEtqFoa0IYXJr/ZDcEYRrcPdNcPHy7gFmuCXuJnmb5Ix4fkw7zTG0cBiitBJoGtDG627Hh8+5sIl8hHUVaSSrRlEUZB7Nro3ZDN0517yhj8J8WE3wcPbndbj2P3IwUZVIGA6WwGBbs0pTBDLEqqWS0c0H+6w66rYIiNFdxbd6YKvwXR1w0YipZXLdnSlkzFSx60CYV/URRwU93bx/bcrMgosA6bE27SznR5H5fU3hDnviNNkM4VzNM1WmlQNRFceJyWXzyYfs7Bbad8WxnVxR0G5EBUWyZqitKCXdP3Swd6yJIOhRIFqzxqnBJRDw7uxef82vG0uJ3kIculouDD/r9xCmEnCSL1kRxZOGhrxoGa2kzF4vNnkqoZZLJBZxVdrv60vxJDiis26shKrXMY+OkX26yvZMC1EfHFR+vrwUJFX4sHMnb0F+yrvSLiLt0e5qm8dKG7yfzGZXQl4bhfvvoBxm6ndaa1TrZ+gCa/pno82qp8I53Vu9knx5iFMRBh7o=
